import Navbar from "@/components/navbar/navbar";
import ProtectedRoute from "@/components/protectRoute/protected_route";
import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <ProtectedRoute>
                    <Navbar />
                    {children}
                </ProtectedRoute>
            </body>
        </html>
    );
}
